
"openapi": "3.1.0"
"info":
  "title": "SDDO Users - Authentication"
  "description": "Contrato de API referente aos recursos relacionado a usuarios que atendem como fonte de dados para o SDDO"
  "license":
    "name": "Apache 2.0"
    "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
  "version": "1.0.0"
"paths":
  "/users/login":
    "post":
      "tags":
        - "Login"
      "summary": "Login de usuário"
      "description": "Faz login em um usuário"
      "operationId": "Login"
      "requestBody":
        "content":
          "application/json":
            "schema":
              $ref: '#/components/schemas/login'
        "required": true
      "responses":
        "200":
          "description": "Ok"
        "400":
          "description": "Ocorreu um erro, veja os detalhes"
          "content":
            "application/json":
              "schema":
                "type": "object"
                "properties":
                  "timestamp":
                    "type": "string"
                    "format": "date-time"
                  "details":
                    "type": "string"
        "500":
          "description": "Ocorreu um erro inesperado"
  "/users/password/recovery":
    post: 
      "tags":
        - "Password"
      "summary": "Solicita recuperação de senha do usuário"
      "description": "Inicia uma solicitação de recuperação de senha de um usuário"
      "operationId": "recover-password"
      "requestBody":
        "content":
          "application/json":
            "schema":
              $ref: '#/components/schemas/recover-password'
        "required": true
      "responses":
        "201":
          "description": "Email enviado e solicitação criada"
          "content":
            "application/json":
              "schema":
                "type": "object"
                "properties":
                    token:
                     type: string
                     pattern: UUID
        "400":
          "description": "Ocorreu um erro, veja os detalhes"
          "content":
            "application/json":
              "schema":
                "type": "object"
                "properties":
                  "timestamp":
                    "type": "string"
                    "format": "date-time"
                  "details":
                    "type": "string"
        "500":
          "description": "Ocorreu um erro inesperado"
    "put":
      "tags":
        - "Password"
      "summary": "Reseta a senha de usuário"
      "description": "Completa o fluxo de reset de senha utilizando um token"
      "operationId": "reset-password"
      "requestBody":
        "content":
          "application/json":
            "schema":
              $ref: '#/components/schemas/reset-password'
        "required": true
      "responses":
        "202":
          "description": "Accepted"
        "400":
          "description": "Ocorreu um erro, veja os detalhes"
          "content":
            "application/json":
              "schema":
                "type": "object"
                "properties":
                  "timestamp":
                    "type": "string"
                    "format": "date-time"
                  "details":
                    "type": "string"
        "500":
          "description": "Ocorreu um erro inesperado"
  "/users/{documentNumber}/password":
    put:
      "tags":
      - "Password"
      "summary": "Atualiza a senha de usuário"
      "description": "Atualiza a senha de um usuário"
      "operationId": "change-password"
      "parameters":
        - in: path
          name: documentNumber
          schema:
            type: string
          required: true
      "requestBody":
        "content":
            "application/json":
              "schema":
                  $ref: '#/components/schemas/password-change'
        "required": true
      "responses":
        "202":
            "description": "Accepted"
        "400":
            "description": "Ocorreu um erro, veja os detalhes"
            "content":
              "application/json":
                  "schema":
                    "type": "object"
                    "properties":
                        "timestamp":
                            "type": "string"
                            "format": "date-time"
                        "details":
                            "type": "string"
        "500":
            "description": "Ocorreu um erro inesperado"
"components":
  "schemas":
    password-change:
        type: object
        properties:
            currentPassword:
                type: string
                format: password
            newPassword:
                type: string
                format: password
    login:
        type: object
        properties:
            email:
                type: string
                format: email
            password:
                type: string
                format: password
    recover-password:
        type: object
        properties:
            email:
                type: string
                format: email
    reset-password:
        type: object
        properties:
            token:
                type: string
                format: UUID
            newPassword:
                type: string
                format: password
  "responses":
    "ErroTratado":
      "description": "Ocorreu um erro, veja os detalhes"
      "content":
        "application/json":
          "schema":
            "type": "object"
            "properties":
              "timestamp":
                "type": "string"
                "format": "date-time"
              "details":
                "type": "string"